# -*- coding: utf-8 -*-
"""newtrain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j_j7CI0YvtoBlmCpQrZ-ZJkmWUReOCyc
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install ultralytics roboflow --quiet

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="lALnORli8jMqO0qiw5Rd")
project = rf.workspace("ilefs-workspace").project("final-jeans-defects-bgfkg")
version = project.version(2)
dataset = version.download("yolov11")

!yolo task=detect mode=train \
model=yolov8s.pt \
data="/content/final-jeans-defects-bgfkg/data.yaml" \
epochs=50 imgsz=640 \
project="/content/drive/MyDrive/yolo_results" \
name="jeans_defect_model"

import os
os.path.exists("/content/final-jeans-defects-bgfkg-2/data.yaml")

!ls /content

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="lALnORli8jMqO0qiw5Rd")
project = rf.workspace("ilefs-workspace").project("final-jeans-defects-bgfkg")
version = project.version(2)
dataset = version.download("yolov11")

print(dataset.location)

!yolo task=detect mode=train \
model=yolov8s.pt \
data="/content/final-jeans-defects-2/data.yaml" \
epochs=50 imgsz=640 \
project="/content/drive/MyDrive/yolo_results" \
name="jeans_defect_model"

from IPython.display import Image, display

display(Image('/content/drive/MyDrive/yolo_results/jeans_defect_model/results.png'))

!ls /content/drive/MyDrive/yolo_results

!ls /content/drive/MyDrive/yolo_results/jeans_defect_model

!ls /content/drive/MyDrive/yolo_results/jeans_defect_model2

from IPython.display import Image, display

display(Image('/content/drive/MyDrive/yolo_results/jeans_defect_model2/results.png'))

display(Image('/content/drive/MyDrive/yolo_results/jeans_defect_model2/confusion_matrix.png'))

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/yolo_results/jeans_defect_model2/results.csv')
df.tail()

project="/content/drive/MyDrive/yolo_results"

from google.colab import files
files.download('/content/drive/MyDrive/yolo_results/jeans_defect_model2/weights/best.pt')

from google.colab import drive
drive.mount('/content/drive')

from ultralytics import YOLO

# Charger le modèle entraîné
model = YOLO("/content/drive/MyDrive/yolo_results/jeans_defect_model2/weights/best.pt")

# Faire la prédiction
results = model.predict(
    source="/content/drive/MyDrive/jean1.jpg",
    conf=0.25,   # Seuil de confiance
    save=True     # Sauvegarder l'image avec boîtes
)

results = model.predict(
    source="/content/drive/MyDrive",  # ton dossier avec toutes les images
    conf=0.25,
    save=True
)

import os
from IPython.display import Image, display

folder = "/content/runs/detect/predict"

for img_file in os.listdir(folder):
    if img_file.endswith((".jpg", ".png")):
        display(Image(os.path.join(folder, img_file)))

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="lALnORli8jMqO0qiw5Rd")
project = rf.workspace("wassimpfe").project("final-jeans-defects")
version = project.version(4)
dataset = version.download("yolov11")

!ls {dataset.location}